"""
Django settings for strongCelery project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import socket

# Get the hostname to make settings conditional to development/deploy
isDeploy = socket.gethostname() == 'server331.web-hosting.com'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open(BASE_DIR / "strongCelery/etc/secret_key.txt") as f:
    SECRET_KEY = f.read().strip()
with open(BASE_DIR / "strongCelery/etc/db_key.txt") as f:
    DB_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
if isDeploy:
    DEBUG = False
    ALLOWED_HOSTS = ['celery.jovanranst.com',
                     'www.celery.jovanranst.com',]
else:
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1',]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
if isDeploy:
    STATIC_ROOT = '/home/jovasqjj/public_html/static'
STATICFILES_DIRS = [BASE_DIR / 'automationHandler/static',]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files are stored under the static folder in developement
# In DEPLOY they are then served under the subdomain
if isDeploy:
    MEDIA_FOLDER = ''
    MEDIA_ROOT = '/home/jovasqjj/media.jovanranst.com/' + 'strongCelery/'
    MEDIA_URL = 'https://media.jovanranst.com/' + 'strongCelery/'
else:
    MEDIA_FOLDER = ''
    MEDIA_ROOT = '/home/jovanranst/projects/ojoiloftrop/automationHandler/' + 'static/uploads/'
    MEDIA_URL = 'automationHandler/'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'automationHandler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'strongCelery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'automationHandler/static/templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

if isDeploy:
    TEMPLATES[0]['DIRS'].append(STATIC_ROOT + 'templates')

WSGI_APPLICATION = 'strongCelery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
if isDeploy:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            # MySQL settings use the name of the db not the path
            'NAME': 'jovasqjj_strongCeleryDB',
            # Name of MySQL user in CPanel
            'USER': 'jovasqjj_jovanranst',
            # MySQL password '*!%password*%#'
            'PASSWORD': DB_KEY,
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
